environment:

  matrix:
    - PYTHON: C:\\Python36
      PYTHON_VERSION: 3.6.7
      PYTHON_ARCH: 32

    - PYTHON: C:\\Python36-x64
      PYTHON_VERSION: 3.6.7
      PYTHON_ARCH: 64

    - PYTHON: C:\\Python37
      PYTHON_VERSION: 3.7.1
      PYTHON_ARCH: 32

    - PYTHON: C:\\Python37-x64
      PYTHON_VERSION: 3.7.1
      PYTHON_ARCH: 64

install:
  - ps: wget https://github.com/alexbahnisch/pyplus/archive/master.zip -OutFile ./master.zip
  - 7z e master.zip */appveyor/* -oappveyor
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - easy_install pip

build: false

before_test:
  - pip install .[appveyor]

test_script:
  - python setup.py test
