site_author: "alex Bahnisch"
site_name: "PyPlus"
repo_url: "https://github.com/alexbahnisch/pyplus"

extra_css:
  - "css/code-highlight.css"
  - "css/dark-theme.css"
  - "css/styles.css"

markdown_extensions:
  - admonition:
  - codehilite:
      linenums: true
  - toc:
      permalink: true

nav:
  - home: "index.md"
  - modules:
    - abstract: "abstract.md"
    - common: "common.md"
    - data: "data.md"
    - decorators: "decorators.md"
    - json: "json.md"
    - object: "object.md"
    - parse: "parse.md"
    - path: "path.md"
    - string: "string.md"
    - table: "table.md"

theme:
  name: "material"
